# Generated by Django 5.0.6 on 2024-10-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_purchase', '0002_remove_purchase_successful_alter_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
