# Generated by Django 5.0.6 on 2024-10-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_purchase', '0003_purchase_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
