# Generated by Django 5.0.6 on 2024-10-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_purchase', '0004_purchase_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
