# Generated by Django 5.0.6 on 2024-12-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin_purchase', '0005_purchase_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinpackage',
            old_name='price',
            new_name='coin_price',
        ),
    ]
