# Generated by Django 5.0.6 on 2024-12-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_auction_end_time_product_is_sold_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
