# Generated by Django 5.0.6 on 2024-12-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_bid_user_alter_bid_bid_amount_alter_bid_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_bids', to='product.bid'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidplacements', to='product.product'),
        ),
    ]
