# Generated by Django 5.0.6 on 2024-12-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_bids_bid_ai_name_alter_bid_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidplacements', to='product.product'),
        ),
    ]
