# Generated by Django 5.0.6 on 2024-12-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_bid_ai_name_alter_bid_product_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_auction_ended',
            field=models.BooleanField(default=False),
        ),
    ]
