# Generated by Django 5.0.6 on 2024-12-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_is_auction_ended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auction_end_time',
        ),
    ]
