# Generated by Django 5.0.6 on 2024-12-29 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_product_auction_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_auction_ended',
        ),
        migrations.AddField(
            model_name='product',
            name='auction_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
