# Generated by Django 5.0.6 on 2024-06-22 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='Enter Address', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
