# Generated by Django 5.0.6 on 2024-07-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_coin_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='coin_balance',
        ),
    ]
