# Generated by Django 5.0.6 on 2024-12-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidPlacement', '0003_remove_bid_ai_name_alter_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
